Repository sindresorhus/file-type, pull requests merged in 2020-02, with the labels that each got.

#319 Deprecate minimumBytes
  browser.d.ts
  core.d.ts
  core.js
  index.d.ts
  index.test-d.ts
  readme.md
  test.js
Labels: API change

#323 src: Add support for AI files (Adobe Illustrator)
  core.d.ts
  core.js
  fixture/fixture.ai
  package.json
  readme.md
  supported.js
Labels: enhancement

#324 Prevent throwing error in `.stream()` on empty stream
  core.js
  test.js
Labels: bug

#329 Fix inconsistent buffer-size declaration in `_checkSequence()`
  core.js
Labels: bug

#334 Fixes bug for short streams where stream ends on first read.
  core.js
  package.json
  test.js
Labels: bug
