Repository sindresorhus/file-type, pull requests merged in 2024-07, with the labels that each got.

#633 Replace node:buffer usage with Uint8Array
  core.d.ts
  core.js
  index.test-d.ts
  package.json
  readme.md
  test.js
  util.js
Labels: API change

#635 Add support for reading from a WebStreams
  .github/workflows/main.yml
  browser.d.ts
  browser.js
  core.d.ts
  core.js
  index.d.ts
  index.js
  index.test-d.ts
  package.json
  readme.md
  test.js
Labels: enhancement, update dependencies, API change

#639 Fix Node.js entry point export `fileTypeFromTokenizer`
  index.js
Labels: bug

#641 Improve Blob, file, and stream method documentation
  core.d.ts
  index.d.ts
  readme.md
Labels: documentation

#645 Update strtok3 to version v8.0.0
  package.json
Labels: update dependencies

#651 Add missing constructor type to `NodeFileTypeParser`
  index.d.ts
Labels: bug

#650 Fix options in combination with function `fileTypeStream()`
  index.js
  readme.md
Labels: bug
