Repository sindresorhus/file-type, pull requests merged in 2025-05, with the labels that each got.

#753 Correct Matroska (video) MIME-type to formal IANA registration
  core.js
Labels: API change

#754 Correct Apache Arrow MIME-type to formal IANA registration
  core.js
Labels: API change

#755 Correct FLAC MIME-type to formal IANA registration
  core.js
  supported.js
Labels: API change

#748 fix: official IANA MIME type for Apache Parquet files
  core.js
  supported.js
Labels: API change

#757 Simplify MIME-type to file-type mapping
  core.js
Labels: debt

#743 Drop Adobe Illustrator (.ai) detection support
  core.js
  fixture/fixture-normal.ai
  fixture/fixture-without-pdf-compatibility.ai
  package.json
  readme.md
  supported.js
  test.js
Labels: API change

#756 Add unit tests comparing supported MIME types and implemented types
  supported.js
  test.js
Labels: debt

#758 Replace Uint8Array.slice() with Uint8Array.subarray()
  core.js
Labels: debt

#759 Centralize fixture traversal
  test.js
Labels: debt

#752 Allow file-type options to be directly passed to exported functions
  core.d.ts
  core.js
  index.d.ts
  index.js
  index.test-d.ts
  readme.md
Labels: debt

#761 Exclude unknown file types from MIME/extension sync test
  test.js
Labels: debt

#646 Ability to detect MPEG when prefixed with some noise
  core.d.ts
  core.js
  fixture/fixture-bad-offset-10.mp3
  fixture/fixture-bad-offset.mp3
  readme.md
  test.js
Labels: improvement

#762 Fix detection of some PAX TAR formats
  core.js
  fixture/fixture-pax.tar
  test.js
Labels: bug
